### ISSUE TITLE
部署在JetsonNano上会报错？

### ISSUE THREAD

**Issue by huwei1024** [yeyupiaoling/Pytorch-MobileFaceNet#7]
错误信息如下，如何解决呢？
Traceback (most recent call last):
  File "infer.py", line 157, in <module>
    predictor = Predictor(args.mtcnn_model_path, args.mobilefacenet_model_path,
  File "infer.py", line 42, in __init__
    self.faces_db = self.load_face_db(face_db_path)
  File "infer.py", line 50, in load_face_db
    imgs, _ = self.mtcnn.infer_image(img)
  File "/home/huwei/github/Pytorch-MobileFaceNet/detection/face_detect.py", line 263, in infer_image
    boxes_c, landmarks = self.detect_onet(im, boxes_c, 0.7)
  File "/home/huwei/github/Pytorch-MobileFaceNet/detection/face_detect.py", line 181, in detect_onet
    tmp = np.zeros((tmph[i], tmpw[i], 3), dtype=np.uint8)
ValueError: negative dimensions are not allowed

**Comment by yeyupiaoling** [comment]
看错误信息应该是输入数据纬度出了问，题解决了吗？我这个先关闭了。
